# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericParameter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('param', models.CharField(max_length=255, unique=True, verbose_name='param')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='value')),
                ('is_deleted', models.BooleanField(verbose_name='is_deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='value')),
                ('is_deleted', models.BooleanField(verbose_name='is_deleted')),
                ('generic_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.GenericParameter')),
            ],
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_deleted', models.BooleanField(verbose_name='is_deleted')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='web_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.WebService'),
        ),
    ]
